Repository team-mozu/mozu-BE-v2, pull requests merged in 2025-08, with the labels that each got.

#12 chore(#11): .editorconfig 추가
  .editorconfig
Labels: ⚙️ setting

#17 Merge/mzbe 55 design organ domain
  src/main/kotlin/team/mozu/dsm/MozuBeV2Application.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/entity/OrganJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/domain/BaseTimeEntity.kt
  src/main/kotlin/team/mozu/dsm/domain/BaseUUIDEntity.kt
  src/main/kotlin/team/mozu/dsm/domain/organ/model/Organ.kt
  src/test/kotlin/team/mozu/dsm/MozuBeV2ApplicationTests.kt
Labels: 🧑‍💻 feat

#22 Merge/mzbe 65 entity refactoring
  src/main/kotlin/team/mozu/dsm/adapter/out/entity/OrganJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/organ/entity/OrganJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/domain/BaseUUIDEntity.kt
  src/main/kotlin/team/mozu/dsm/global/entity/BaseTimeEntity.kt
  src/main/kotlin/team/mozu/dsm/global/entity/BaseUUIDEntity.kt
Labels: ♻️ refactor

#33 Merge/mzbe 77 design article domain
  src/main/kotlin/team/mozu/dsm/adapter/out/article/entity/ArticleJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/article/persistence/mapper/ArticleMapper.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/article/persistence/repository/ArticleRepository.kt
  src/main/kotlin/team/mozu/dsm/domain/article/model/Article.kt
Labels: 🧑‍💻 feat

#42 Merge/mzbe 85 hold item domain design
  src/main/kotlin/team/mozu/dsm/adapter/out/article/entity/ArticleJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/article/persistence/mapper/ArticleMapper.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/entity/ItemJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/persistence/mapper/ItemMapper.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/entity/StockJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/mapper/StockMapper.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/repository/StockRepository.kt
  src/main/kotlin/team/mozu/dsm/domain/article/model/Article.kt
  src/main/kotlin/team/mozu/dsm/domain/item/model/Item.kt
  src/main/kotlin/team/mozu/dsm/domain/team/model/Stock.kt
Labels: 🧑‍💻 feat

#45 Merge/mzbe 52 set sse
  src/main/kotlin/team/mozu/dsm/adapter/in/sse/SseWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/entity/ItemJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/sse/SsePersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/sse/repository/SseEmitterRepository.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/sse/PublishToAllSseUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/sse/PublishToSseUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/sse/SubscribeSseUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/sse/PublishSsePort.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/sse/SubscribeSsePort.kt
  src/main/kotlin/team/mozu/dsm/application/sse/PublishToAllSseService.kt
  src/main/kotlin/team/mozu/dsm/application/sse/PublishToSseService.kt
  src/main/kotlin/team/mozu/dsm/application/sse/SubscribeSseService.kt
  src/main/kotlin/team/mozu/dsm/global/error/exception/ErrorCode.kt
  src/main/kotlin/team/mozu/dsm/global/error/sse/SseExceptionHandler.kt
  src/main/kotlin/team/mozu/dsm/global/exception/sse/InvalidSseDataException.kt
  src/main/kotlin/team/mozu/dsm/global/exception/sse/InvalidSseStateException.kt
  src/main/kotlin/team/mozu/dsm/global/exception/sse/SseConnectionClosedException.kt
  src/main/kotlin/team/mozu/dsm/global/exception/sse/UnknownSseErrorException.kt
Labels: ⚙️ setting

#55 Merge/mzbe 95 create organ
  src/main/kotlin/team/mozu/dsm/adapter/in/organ/OrganWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/organ/dto/request/CreateOrganRequest.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/organ/entity/OrganJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/organ/persistence/OrganPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/organ/CreateOrganUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/organ/CommandOrganPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/organ/CreateOrganService.kt
  src/main/kotlin/team/mozu/dsm/application/service/sse/PublishToAllSseService.kt
  src/main/kotlin/team/mozu/dsm/application/service/sse/PublishToSseService.kt
  src/main/kotlin/team/mozu/dsm/application/service/sse/SubscribeSseService.kt
  src/main/kotlin/team/mozu/dsm/domain/organ/model/Organ.kt
  src/main/kotlin/team/mozu/dsm/global/config/security/SecurityConfig.kt
Labels: 🧑‍💻 feat

#57 Merge/mzbe 100 team participate api
  src/main/kotlin/team/mozu/dsm/adapter/in/team/TeamWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/team/dto/TeamParticipationEventDTO.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/team/dto/request/TeamParticipationRequest.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonQueryPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/mapper/LessonMapper.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/repository/LessonRepository.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/entity/TeamJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/TeamCommandPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/mapper/TeamMapper.kt
  src/main/kotlin/team/mozu/dsm/application/exception/lesson/LessonCreatedAtNotFoundException.kt
  src/main/kotlin/team/mozu/dsm/application/exception/lesson/LessonDeletedException.kt
  src/main/kotlin/team/mozu/dsm/application/exception/lesson/LessonNotFoundException.kt
  src/main/kotlin/team/mozu/dsm/application/exception/lesson/LessonNotInProgressException.kt
  src/main/kotlin/team/mozu/dsm/application/exception/lesson/LessonNumNotFoundException.kt
  src/main/kotlin/team/mozu/dsm/application/exception/lesson/TeamNameRequiredException.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/team/TeamParticipationUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/team/dto/request/TeamParticipationCommand.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/team/dto/response/TeamToken.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/auth/JwtPort.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/LessonQueryPort.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/team/TeamCommandPort.kt
  src/main/kotlin/team/mozu/dsm/application/team/TeamParticipationService.kt
  src/main/kotlin/team/mozu/dsm/domain/team/model/Team.kt
  src/main/kotlin/team/mozu/dsm/global/config/security/SecurityConfig.kt
  src/main/kotlin/team/mozu/dsm/global/error/exception/ErrorCode.kt
  src/main/kotlin/team/mozu/dsm/global/security/jwt/JwtAdapter.kt
Labels: 🧑‍💻 feat

#67 Fix/mzbe 111 reissue organ token
  src/main/kotlin/team/mozu/dsm/adapter/in/organ/OrganWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/auth/persistence/RefreshTokenPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/auth/persistence/repository/RefreshTokenRepository.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/auth/CommandTokenPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/organ/ReissueOrganTokenService.kt
Labels: 👾 BUG

#74 Merge/mzbe 117 start lesson
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/dto/response/StartLessonResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/repository/LessonRepository.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/organ/persistence/OrganPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/entity/TeamJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/StartLessonUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/CommandLessonPort.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/QueryLessonPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/StartLessonService.kt
Labels: 🧑‍💻 feat

#82 Merge/mzbe 121 change isstarred status
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/ChangeStarredUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/CommandLessonPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/ChangeStarredService.kt
Labels: 🧑‍💻 feat
