Repository team-mozu/mozu-BE-v2, pull requests merged in 2025-09, with the labels that each got.

#93 Merge/mzbe 104 create item
  src/main/kotlin/team/mozu/dsm/adapter/in/item/ItemWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/item/dto/request/ItemRequest.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/item/dto/response/ItemResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/persistence/ItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/item/CreateItemUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/item/CommandItemPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/CreateItemService.kt
Labels: 🧑‍💻 feat

#90 Merge/mzbe 115 query organ inventory
  src/main/kotlin/team/mozu/dsm/adapter/in/organ/OrganWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/organ/dto/response/OrganListResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/organ/persistence/OrganPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/organ/QueryOrganInventoryUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/organ/QueryOrganPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/organ/QueryOrganInventoryService.kt
  src/main/kotlin/team/mozu/dsm/global/config/security/SecurityConfig.kt
Labels: 🧑‍💻 feat

#99 Merge/mzbe 133 get lesson detail
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonArticlePersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/repository/LessonArticleRepository.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/repository/LessonItemRepository.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/GetLessonDetailUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/QueryLessonArticlePort.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/QueryLessonItemPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/GetLessonDetailService.kt
Labels: 🧑‍💻 feat

#104 Merge/mzbe 134 get lesson list
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/dto/response/LessonListResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/GetLessonsUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/QueryLessonPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/GetLessonsService.kt
Labels: 🧑‍💻 feat

#106 Merge/mzbe 143 get order item
  src/main/kotlin/team/mozu/dsm/adapter/in/team/TeamWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/team/dto/request/CompleteInvestmentRequest.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/team/dto/response/OrderItemResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/entity/OrderItemJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/OrderItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/StockPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/mapper/OrderItemMapper.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/repository/OrderItemRepository.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/team/GetOrderItemUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/team/QueryOrderItemPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/GetLessonDetailService.kt
  src/main/kotlin/team/mozu/dsm/application/service/team/CompleteTeamInvestmentService.kt
  src/main/kotlin/team/mozu/dsm/application/service/team/GetOrderItemService.kt
  src/main/kotlin/team/mozu/dsm/domain/team/model/OrderItem.kt
  src/main/kotlin/team/mozu/dsm/global/config/security/SecurityConfig.kt
Labels: 🧑‍💻 feat

#109 Merge/mzbe 152 get lesson item
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/organ/persistence/OrganPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/GetLessonItemsUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/GetLessonItemsService.kt
Labels: 🧑‍💻 feat

#112 Merge/mzbe 153 get lesson articles
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/GetLessonArticlesUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/GetLessonArticlesService.kt
Labels: 🧑‍💻 feat

#97 Merge/mzbe 137 delete item
  src/main/kotlin/team/mozu/dsm/adapter/in/item/ItemWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/entity/ItemJpaEntity.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/persistence/ItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/item/DeleteItemUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/item/CommandItemPort.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/item/QueryItemPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/DeleteItemService.kt
Labels: 🧑‍💻 feat

#111 Merge/mzbe 139 query item
  src/main/kotlin/team/mozu/dsm/adapter/in/item/ItemWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/item/dto/response/ItemResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/persistence/ItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/persistence/mapper/ItemMapper.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/item/QueryItemAllUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/item/QueryItemDetailUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/item/QueryItemPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/CreateItemService.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/QueryItemAllService.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/QueryItemDetailService.kt
Labels: 🧑‍💻 feat

#121 Merge/mzbe 145 get team rank
  src/main/kotlin/team/mozu/dsm/adapter/in/team/TeamWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/team/dto/response/TeamRankResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/TeamPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/team/GetTeamRanksUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/team/QueryTeamPort.kt
  src/main/kotlin/team/mozu/dsm/application/service/team/CompleteTeamInvestmentService.kt
  src/main/kotlin/team/mozu/dsm/application/service/team/GetTeamRanksService.kt
  src/main/kotlin/team/mozu/dsm/application/service/team/GetTeamResultService.kt
  src/main/kotlin/team/mozu/dsm/global/config/security/SecurityConfig.kt
Labels: 🧑‍💻 feat

#133 Merge/mzbe 171 get lesson round articles
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/dto/response/LessonRoundArticleResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonArticlePersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/GetLessonRoundArticlesUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/QueryLessonArticlePort.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/GetLessonRoundArticlesService.kt
Labels: 🧑‍💻 feat

#140 Merge/mzbe 170 get lesson item detail
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/LessonWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/dto/response/LessonItemDetailResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/lesson/dto/response/LessonRoundArticleResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/GetLessonItemDetailUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/lesson/GetLessonRoundItemsUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/QueryLessonItemPort.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/dto/LessonItemDetailProjection.kt
  src/main/kotlin/team/mozu/dsm/application/port/out/lesson/dto/LessonRoundItemProjection.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/GetLessonItemDetailService.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/GetLessonRoundArticlesService.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/LessonOrganSSEService.kt
Labels: 🧑‍💻 feat

#144 Merge/mzbe 186 connect team sse
  src/main/kotlin/team/mozu/dsm/adapter/in/team/TeamWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/persistence/ItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/lesson/persistence/LessonArticlePersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/team/persistence/OrderItemPersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/team/ConnectTeamSSEUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/service/lesson/facade/LessonFacade.kt
  src/main/kotlin/team/mozu/dsm/application/service/team/CompleteTeamInvestmentService.kt
  src/main/kotlin/team/mozu/dsm/application/service/team/ConnectTeamSSEService.kt
  src/main/kotlin/team/mozu/dsm/global/config/security/SecurityConfig.kt
Labels: 🧑‍💻 feat

#153 Feature/mzbe 190 set swagger
  src/main/kotlin/team/mozu/dsm/global/document/article/ArticleApiDocument.kt
  src/main/kotlin/team/mozu/dsm/global/document/item/ItemApiDocument.kt
  src/main/kotlin/team/mozu/dsm/global/document/lesson/LessonApiDocument.kt
  src/main/kotlin/team/mozu/dsm/global/document/organ/OrganApiDocument.kt
  src/main/kotlin/team/mozu/dsm/global/document/team/TeamApiDocument.kt
Labels: ♻️ refactor

#155 Fix
  src/main/kotlin/team/mozu/dsm/adapter/in/item/ItemWebAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/in/item/dto/response/ItemQueryResponse.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/item/persistence/mapper/ItemMapper.kt
  src/main/kotlin/team/mozu/dsm/application/port/in/item/QueryItemAllUseCase.kt
  src/main/kotlin/team/mozu/dsm/application/service/article/DeleteArticleService.kt
  src/main/kotlin/team/mozu/dsm/application/service/article/UpdateArticleService.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/DeleteItemService.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/QueryItemAllService.kt
  src/main/kotlin/team/mozu/dsm/application/service/item/UpdateItemService.kt
  src/main/kotlin/team/mozu/dsm/global/document/item/ItemApiDocument.kt
Labels: ♻️ refactor

#161 Article update 수정
  src/main/kotlin/team/mozu/dsm/adapter/out/article/persistence/ArticlePersistenceAdapter.kt
  src/main/kotlin/team/mozu/dsm/adapter/out/article/persistence/mapper/ArticleMapper.kt
  src/main/kotlin/team/mozu/dsm/application/service/article/UpdateArticleService.kt
  src/main/kotlin/team/mozu/dsm/domain/article/model/Article.kt
Labels: 👾 BUG
